### ISSUE TITLE
Config Name Is Incorrect For Data Source In Documentation

### ISSUE THREAD

**Issue by truly-indian** [dekart-xyz/dekart#189]
The name of the config is incorrect in the documentation if you want to provide PG Data source. We should fix the name in the documentation.

**Comment by Tsovak** [comment]
hello @truly-indian , thanks for opening issue.
we have Dekart database for storing metadata and **DEKART_POSTGRES_DATA_CONNECTION** to manage only data to visualize. 
what do you mean it is incorrect? 
as I understood, you want to extend the name from DEKART_POSTGRES_DATA_CONNECTION to  DEKART_POSTGRES_DATA**SOURCE**_CONNECTION

**Comment by truly-indian** [comment]
@Tsovak As you mentioned you have DEKART_POSTGRES_DATA_CONNECTION to manage only data to visualize. What I am saying is that in the code where you are connecting to PG you are using the config name as DEKART_POSTGRES_DATASOURCE_CONNECTION and in the documentation you are stating the config to be used as DEKART_POSTGRES_DATA_CONNECTION which is misleading and wasting a lot of developer time.

Please refer this line of code. The config name used here for pg connection is wrongly mentioned in the documentation. https://github.com/dekart-xyz/dekart/blob/2c1ac7163e55be66647f232bdb289dc662649f2f/src/server/pgjob/pgjob.go#L31

**Comment by Tsovak** [comment]
> @Tsovak As you mentioned you have DEKART_POSTGRES_DATA_CONNECTION to manage only data to visualize. What I am saying is that in the code where you are connecting to PG you are using the config name as DEKART_POSTGRES_DATASOURCE_CONNECTION and in the documentation you are stating the config to be used as DEKART_POSTGRES_DATA_CONNECTION which is misleading and wasting a lot of developer time.
> 
> Please refer this line of code. The config name used here for pg connection is wrongly mentioned in the documentation.
> 
> https://github.com/dekart-xyz/dekart/blob/2c1ac7163e55be66647f232bdb289dc662649f2f/src/server/pgjob/pgjob.go#L31

I see. It's my mistake. 
In the code, it calls DATASOURCE_CONNECTION in the env variable called DATA_CONNECTION in documentation as well.


it should be called  DATASOURCE to keep a naming convention consistent with other parts of the project. 
Thanks a lot for contributing to the project.

**Comment by Tsovak** [comment]
the related PR opened to fix the documentation https://github.com/dekart-xyz/www/pull/35

**Comment by delfrrr** [comment]
Great, merged doc PR, thank @Tsovak , @truly-indian
