### ISSUE TITLE
Dekart stop working with no error messages (deadlock)

### ISSUE THREAD

**Issue by philipmargeotab** [dekart-xyz/dekart#25]
Our team set up Dekart.xyz on our own GCP using the instructions provided in https://dekart.xyz/docs/self-hosting/app-engine/, using Google App Engine. However, an issue we are running into is - whenever we run an invalid query, no error message comes up (either in Dekart or in the docker logs), and we have to reset the docker image every time, and only then do we see the error message. Is there better error handling available that doesn't cause Dekart to crash every time we submit a query with syntax or permissions errors (e.g. a column doesn't exist, or a user doesn't have permission to a table). The crash also prevents users from returning to the home 'reports' screen. It goes completely blank.

**Comment by philipmargeotab** [comment]
Some example errors (with identifying data removed):

googleapi: Error 403: Access Denied
googleapi: Error 404: Not found
googleapi: Error 400: Unrecognized name

these errors caused the self-hosted website to crash.

**Comment by delfrrr** [comment]
Hey @philipmargeotab  will try to help you. I'm running Dekart instance on GCP for the Playground, so it should be possible.

Can you please tell:
* which version do you use
* copy here `app.yaml` (without sensitive details of course)

Also can you please set `DEKART_LOG_DEBUG: "1"` in `env_variables` and share here logs

**Comment by philipmargeotab** [comment]
Version is 0.7
###

# https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#intro
service: dekart-test
runtime: custom
env: flex

manual_scaling:
   instances: 1 # important as dekart designed to work on single instance

resources:
   memory_gb: 64.0 # recommended to handle up to 1M points
   cpu: 16
   disk_size_gb: 100

env_variables:
  DEKART_LOG_DEBUG: "1"
  DEKART_POSTGRES_DB: "dekart"
  DEKART_POSTGRES_USER: "postgres"
  DEKART_POSTGRES_PASSWORD: "dekart"
  DEKART_POSTGRES_PORT: "5432"
  # see https://cloud.google.com/sql/docs/mysql/connect-app-engine-flexible
  DEKART_POSTGRES_HOST: "10.x.x.x" # UNKNOWN
  DEKART_CLOUD_STORAGE_BUCKET: "geotab-dekart-test"  # "$BUCKET"
  DEKART_BIGQUERY_PROJECT_ID: "test-xx"  # "$PROJECT_ID"
  DEKART_MAPBOX_TOKEN: "pk.eyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #
  # "$MAPBOX_TOKEN"

beta_settings:
  # see https://cloud.google.com/sql/docs/mysql/connect-app-engine-flexible
   cloud_sql_instances: "test-xx:europe-west1:dekart-db=tcp:5432"
   # "$PROJECT_ID:europe-west1:$DB_INSTANCE_NAME=tcp:5432"

###

**Comment by delfrrr** [comment]
Hey I think I did manage to reproduce problem, will keep you posted here

**Comment by delfrrr** [comment]
I was able to reproduce dead lock here https://github.com/dekart-xyz/dekart/blob/v0.7.0/src/server/report/report.go#L36
Getting my head around it

**Comment by delfrrr** [comment]
Hey so I believe that problem was with a deadlock. In Dekart there is of course a lot error handling but deadlock formally is not an error. It's not easy to reproduce locally.

I found few potential issues in the code and address them https://github.com/dekart-xyz/dekart/commit/d4395ced927fa4e2e74d6a8acc17d21cf658cca5

@philipmargeotab could you pease update Dekart to `0.7.2` and share a feedback if issue still reproducing

**Comment by philipmargeotab** [comment]
Yes it appears to work now; no more deadlock. Thank you!

**Comment by delfrrr** [comment]
Great!

**Comment by delfrrr** [comment]
Fixed in `0.7.2`
