### ISSUE TITLE
More visible "data view" when clicking a point/polygon

### ISSUE THREAD

**Issue by LangdalP** [dekart-xyz/dekart#30]
Hi!

I have a use case where I want to be able to click a geography, and copy an associated ID (which is also shown in the tooltip). The problem is that the "data view" that pops up when you click the point appears below the view port. This means that it is both:

1. Hard to notice that it even exists
2. You have to scroll down to it, which is tiresome.

If you are unsure of what I mean, see the screenshot.

Is there a way to fix this? I would be willing to attempt to create a PR if you agree that this is something that could be improved and we agree on a reasonable new behaviour when one clicks a geography.

Screenshot:
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/6378834/158081671-18bda7b2-1e08-4c94-ae68-fe895d61b13a.png">

**Comment by delfrrr** [comment]
Looks a lot like a bug, should appear under the pointer

**Comment by LangdalP** [comment]
Are you sure you are not thinking about the tooltip? That shows under the pointer when you hover over it. But when you click it, the box shown on the screenshot pops up.

**Comment by kevinjamesparks** [comment]
@LangdalP, based on your last comment, can you confirm this is a bug coming from kepler.gl?
We'll still have a further look if we can resolve this.

**Comment by delfrrr** [comment]
This is still strange behavior

<img width="1624" alt="Screenshot 2023-06-05 at 22 13 27" src="https://github.com/dekart-xyz/dekart/assets/495642/a01514b0-0046-4b79-94c0-a50ad2388d13">

**Comment by delfrrr** [comment]
Hey @LangdalP finally fixed this issue. Fix is available in release candidate `v0.14.0-rc.2`
If you keep using or considering Dekart, please join our Slack Community http://slack.dekart.xyz/
I will be happy to hear your feedback on new feature development.
