### ISSUE TITLE
Support for exporting/printing a map

### ISSUE THREAD

**Issue by delfrrr** [dekart-xyz/dekart#31]
Similar to https://data.apps.fao.org/ (Use Printing -> Custom Print)

**Comment by nanodan** [comment]
It looks like exporting is available as a feature kepler for a while; is there a reason this isn't exposed in dekart?

**Comment by pooriaPoorsarvi** [comment]
This change should fix the issue https://github.com/dekart-xyz/dekart/pull/72 @delfrrr @nanodan

**Comment by delfrrr** [comment]
This should be resolved by #106

**Comment by delfrrr** [comment]
Let me know how does it work.

![output](https://github.com/dekart-xyz/dekart/assets/495642/fa626534-6e81-4c43-bd9b-466d383e7052)
