### ISSUE TITLE
Retrieve results from BigQuery Scripts

### ISSUE THREAD

**Issue by nanodan** [dekart-xyz/dekart#69]
**Reproduce:** Write a query that uses SQL scripting, then execute

**Expected behaviour:** Dekart retrieves the results of the query

**Actual behaviour:** Dekart returns a ["destination table is nil" error,](https://github.com/dekart-xyz/dekart/blob/b1c6f0e6933f4c012da95414bd9b813ceebd7756/src/server/bqjob/job.go#L134) as SQL scripts do not have a destination table in the job config.

There are other ways to retrieve a query result by job ID that don't require a destination table in the JobConfig which would allow results retrieval for both regular SQL and SQL scripting jobs.

**Comment by delfrrr** [comment]
Hey @nanodan, thank you for reaching out.

* Does your query assume any data to be returned?
* If yes, can you please give an example of query against BigQuery public dataset, so we can reproduce?

**Comment by nanodan** [comment]
Yes this can be easily replicated with any script, no need for any BigQuery dataset. For example the following will fail, despite returning a valid WKT row:

```
DECLARE var_Example INT64 DEFAULT 1;

select ST_GEOGPOINT(-72, 51) as GeoPoint
```

@pooriaPoorsarvi has sent a [pull request](https://github.com/dekart-xyz/dekart/pull/71) which resolves this issue by getting the destination table via job ID instead of directly via the job object (in which case the destination table doesn't exist for jobs which are also scripts).

**Comment by delfrrr** [comment]
@nanodan amazing, reviewing PR asap

**Comment by delfrrr** [comment]
PR merged, I will shortly merge next PR and build release candidate you can use. Then I will add e2e test for this use case and close the issue.

**Comment by nanodan** [comment]
Great thanks! Looking forward to using this project and contributing, it's a very useful tool.
