### ISSUE TITLE
feature request: set custom name for queries

### ISSUE THREAD

**Issue by Tsovak** [dekart-xyz/dekart#73]
Small feature request. 
I have multiple different queries, which use 3 different tables. It’s confusing to know which data set is which table/query if they are just called “Query 1”, “Query 2", “Query 3”.. would be cool to be able to change that.

**Comment by nanodan** [comment]
Duplicate of #68

**Comment by Tsovak** [comment]
Duplicate of https://github.com/dekart-xyz/dekart/issues/68
