### ISSUE TITLE
Show filters in report view

### ISSUE THREAD

**Issue by zainearnest** [dekart-xyz/dekart#9]
It would be nice to have the filters available in the view mode of the report

**Comment by delfrrr** [comment]
@zainearnest hey, thank you for the feedback!

The thing is that report also includes map configuration, which includes current state of filters.

What is the expected behaviour when changing filters in a view mode?
* they are saved
* they are not saved?
* other?

**Comment by delfrrr** [comment]
Since [release 0.4](https://github.com/dekart-xyz/dekart/releases/tag/v0.4.0) you have filter available in present mode and also for read-only reports; see example [on playground](https://play.dekart.xyz/reports/133d7282-352e-4be7-92bd-c993309675d0)
