### ISSUE TITLE
[Feature] Specify Athena workgroup as an environment variable

### ISSUE THREAD

**Issue by seanlane** [dekart-xyz/dekart#99]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing Dekart functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When submitting queries to be ran by AWS Athena, one optional parameter is the [workgroup](https://docs.aws.amazon.com/athena/latest/ug/manage-queries-control-costs-with-workgroups.html) that will run the query. Specifying the workgroup can have a material impact on a query, since it affects things like IAM permissions, the Athena engine version being used, etc.

I would propose that a new environment variable like `DEKART_ATHENA_WORKGROUP` be created and used when starting a new query execution, and alternatively use the default value of `primary` when not set, since that's what's implicitly being used now.

### Who will this benefit?

Any Dekart users that utilize AWS Athena for their analytics engine.

### Are you interested in contributing this feature?

Yes, I can probably add it. Wanted to make sure this is something that wouldn't be rejected for whatever reason before starting it.

### Anything else?

Wanted to add a thank you for all of the work that's previously been done, Dekart is a great project!

**Comment by delfrrr** [comment]
@seanlane yes, let's do it. I will plan the feature.
